### ISSUE TITLE
Fix website URL's to fetch images from correct address

### ISSUE THREAD

**Issue by uaorob** [ignitioncoin/ignitioncoin#14]
Current urls: `https://45.32.131.126/wp-content/uploads/2018/01/cropped-splash.png`

Change to: `https://ignitioncoin.org/wp-content/uploads/2018/01/cropped-splash.png`

![ignition-debug](https://user-images.githubusercontent.com/35299082/35312193-0275edba-00c3-11e8-8015-0ebb203e05f3.png)

**Comment by TechniumUnlimited** [comment]
Fixed thanks
