### ISSUE TITLE
GUI Displaying Incorrect IC Values

### ISSUE THREAD

**Issue by TechniumUnlimited** [ignitioncoin/ignitioncoin#2]
Confirmed on MacOS - possible on windows, not reported on linux builds

Block Explorer & network detects correct amount while wallet and console debug displays incorrect value.

**Comment by ignitioncoin** [comment]
A debug log from Mac OS - [debug.log](https://github.com/ignitioncoin/ignitioncoin/files/1608141/debug.log)

**Comment by RealAtix** [comment]
Starting from "2018-01-05 22:01:37 Ignition version v1.0.0.1-60028 (Jan  1 2018, 13:08:19)" in debug log.

I had the same issue on Windows after running the wallet for a while. On MacOs it showed the wrong amount at startup.

**Comment by hashtohash** [comment]
Debug log of this issue starts at "2018-01-05 22:01:37 Ignition version v1.0.0.1-60028 (Jan  1 2018, 13:08:19)".

I had the same problem on Windows 10 (VM) after running the wallet for a while. On MacOs it showed the incorrect amount at startup.

**Comment by TechniumUnlimited** [comment]
Current fix is to go to Help -> Debug Console, click the console tab, and then type repairwallet

**Comment by TechniumUnlimited** [comment]
Reported now on Linux CLI as well, meaning issue unlikely to be found in GUI code

**Comment by hashtohash** [comment]
Ubuntu 16.04 CLI - [ic-balance-debug.log](https://github.com/ignitioncoin/ignitioncoin/files/1658182/ic-balance-debug.log)
Issue started somewhere between 2018-01-22 and 2018-01-24

**Comment by TechniumUnlimited** [comment]
Can we just make the wallet every X hours run the command "repairwallet" on itself?

**Comment by Matthematic** [comment]
That would work as an intermittent fix until the real solution is found. How intensive of an operation is that?

**Comment by TechniumUnlimited** [comment]
@Matthematic @sarkawt909 @Miladinho -- Can we get a branch going this week with a first try fix to test :)

**Comment by TechniumUnlimited** [comment]
Only seems to occur when staking

**Comment by TechniumUnlimited** [comment]
Havent had a report of this occurring in a long time. Closing unless more issue's appear in the future
