### ISSUE TITLE
Cannot build Ignitiond file

### ISSUE THREAD

**Issue by mocap3069** [ignitioncoin/ignitioncoin#39]
I have download and gone through the steps multiple time but the Ignitiond
never appears. I also am not getting any errors so not sure how to fix this issue.
Here is where the building ends: /home/mocap3069/ignitioncoin/src/leveldb/libmemenv.a
I changed the permissions so there is not read only errors I received building other wallets.
Any ideas?

**Comment by TechniumUnlimited** [comment]
Hi, for that issue all you need to do is sudo chmod +x the scripts (or the entirety) of whats inside the leveldb folder (and possibly the other libs)

but, the process changed this update but the docs haven't, sorry, there is now a folder in the root of the repo called /bins/ , should go to there when compile is finished.

**Comment by mocap3069** [comment]
I was able to get it running but it will not connect to the network. I can run the Windows version with no issues and added the peers that are working to the Linux conf file but keep getting non connected? Are MasterNodes better than peers?

**Comment by TechniumUnlimited** [comment]
Not sure can you put your debug log here and OS and all other relevant info you can find? 👍

**Comment by TechniumUnlimited** [comment]
Closing as seems issue is solved
