### ISSUE TITLE
Wallet locks completely (rather than goes back to Unlocked for Staking) when sending transaction 

### ISSUE THREAD

**Issue by TechniumUnlimited** [ignitioncoin/ignitioncoin#50]
Wallet locks completely (rather than goes back to Unlocked for Staking) when sending transaction - So if you start from an Unlocked for Staking only state, and send a tx' - it prompts you to unlock the wallet - after you send, it fully locks it and staking stops, rather than going back to the previous state.

**Comment by bekman1** [comment]
simple find from where come a wrong call of wallet lock function

**Comment by e-goz** [comment]
If the issue is still open, I'd like to deal with this one

**Comment by TechniumUnlimited** [comment]
@e-goz sounds good - fork Ignition repo, make changes and we can test from there - thanks

**Comment by TechniumUnlimited** [comment]
... sorry 💃

**Comment by TechniumUnlimited** [comment]
Can we confirm this still occurs?
