### ISSUE TITLE
GUI assert error on close

### ISSUE THREAD

**Issue by TechniumUnlimited** [ignitioncoin/ignitioncoin#57]
https://media.discordapp.net/attachments/413891353815023616/463634356020445184/unknown.png

Not a big issue, but appears is the error above when closing often.

**Comment by fopat** [comment]
**First analysis:**

The assertion happens in the destructor of the LockedPageManagerBase class.
Description of this class: Thread-safe class to keep track of locked (ie, non-swappable) memory pages.

The assertion means that there are still locked memory pages when exiting IC.
The pages seem to be locked only in crypting operations (crypter.h, key.h, etc.).

**Comment by fopat** [comment]
It may be linked to a out of memory issue: https://bitcointalk.org/index.php?topic=826731.0

**Comment by TechniumUnlimited** [comment]
Does the mxe-compile allow for 64 and 32bit compiles?

**Comment by TechniumUnlimited** [comment]
This issue doesnt seem to exist anymore, though, not sure why. Havent encountered it since this day - and, closing.
