### ISSUE TITLE
Implement Built-In Auto-Send On Recive Feature

### ISSUE THREAD

**Issue by TechniumUnlimited** [ignitioncoin/ignitioncoin#66]
DigiWage wallet apparently has an option under Setting and Multisend that you can set to automatically send % of Stakes or MN Rewards to another address. As soon as confirmations clear it sends coins to where you set it up in there.

This remedies and works as a great compromise to the previous auto-split feature that was removed for masternode hardening

**Comment by Zurginator** [comment]
Awesome, Thanks guys!
