### ISSUE TITLE
Masternode reward not sent to specified reward address.

### ISSUE THREAD

**Issue by miningallday1** [ignitioncoin/ignitioncoin#8]
Using this method: https://www.ignitioncoin.org/index.php/remote-masternode-setup-guide/

The masternode rewards are being placed in the address that contains the 3000 IC. The rewards are not being sent to the address specified in masternode.conf file.

**Comment by TechniumUnlimited** [comment]
@mrfixit5 reproduced on accident by having his cold wallet go offline I believe -- Can you post your debug logs from your VPS or Local Ignition wallets @miningallday1 ? ty

**Comment by AmirWaleed** [comment]
[debug (7).log](https://github.com/ignitioncoin/ignitioncoin/files/1709160/debug.7.log)

Raz reported MN rewards were paying out correctly until PC was restarted - Debug log attached

**Comment by TechniumUnlimited** [comment]
Raz in discord reported when this issue occurred for him when he restarted his controller wallet PC - 
[debug (7).log](https://github.com/ignitioncoin/ignitioncoin/files/1709161/debug.7.log)

**Comment by mrfixit5** [comment]
I've tested this fully in TESTNET.   It works great if the controller wallets are behind same IP from what I can tell.  If you setup a few folders and run from '-datadir=./data' you can set the reward address and percentage to send to node behind same IP or external IP even, regardless whether it's the paired MN worker, or another wallet.   However, I cannot get it to work proper from masternode controller wallet on QT -> external IP.  works -  [Quick setup that does work, controller wallet (QT) + MN worker (QT) behind same IP sending rewards to external VPS node]

**Comment by mrfixit5** [comment]
After setting up a true working hot/cold masternode, this issue seems to be non-existent.  rewards send where you request each time as noted in masternode.conf.  Perhaps non-issue if official masternode setup becomes this method that one of our discord members posted. https://crypto101.info/blog/masternode-installation-guide-for-exclusivecoin  

I have switched to this method in production and it works fine as well.

**Comment by TechniumUnlimited** [comment]
@mrfixit5 Do you think this issue should be closed then or could we add more features that will direct users in the correct direction 100% of the time to make sure it works?
