### ISSUE TITLE
Wallet won't switch to staking: true after unlocking

### ISSUE THREAD

**Issue by TechniumUnlimited** [ignitioncoin/ignitioncoin#9]
Reported on linux only at the moment - Unlocking for staking does not enable staking in the Linux CLI

**Comment by hashtohash** [comment]
There seems to be a timeout limit of 14 digits (thanks @mrfixit5)
Should throw an error message if over the limit

**Comment by TechniumUnlimited** [comment]
Will leave issue open until an error is thrown or it becomes capable of handling larger integers.

**Comment by TechniumUnlimited** [comment]
Addressed in latest PR merge: https://github.com/ignitioncoin/ignitioncoin/pull/28
